// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlLrg3cUGqcFqavRenuGjagaLHiSB90oA',
    appId: '1:560625377668:android:24ab672a8654fe0edabdd1',
    messagingSenderId: '560625377668',
    projectId: 'techogachat',
    storageBucket: 'techogachat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCQ9ok0oJ0rb5qK17-f-yuMrK0odCP-4Q',
    appId: '1:560625377668:ios:d63781b8f1d3f65edabdd1',
    messagingSenderId: '560625377668',
    projectId: 'techogachat',
    storageBucket: 'techogachat.appspot.com',
    iosBundleId: 'com.example.techogachat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFflJtgOWXMZlgAAv2YMb0FvP_8RM_WsY',
    appId: '1:560625377668:web:49d1665ad912bee4dabdd1',
    messagingSenderId: '560625377668',
    projectId: 'techogachat',
    authDomain: 'techogachat.firebaseapp.com',
    storageBucket: 'techogachat.appspot.com',
    measurementId: 'G-8YH1K33CJP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCQ9ok0oJ0rb5qK17-f-yuMrK0odCP-4Q',
    appId: '1:560625377668:ios:d63781b8f1d3f65edabdd1',
    messagingSenderId: '560625377668',
    projectId: 'techogachat',
    storageBucket: 'techogachat.appspot.com',
    iosBundleId: 'com.example.techogachat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFflJtgOWXMZlgAAv2YMb0FvP_8RM_WsY',
    appId: '1:560625377668:web:b6dce1d949db01a6dabdd1',
    messagingSenderId: '560625377668',
    projectId: 'techogachat',
    authDomain: 'techogachat.firebaseapp.com',
    storageBucket: 'techogachat.appspot.com',
    measurementId: 'G-ZZX6RMDY7P',
  );

}